xenapi: Exit immediately if zipball download fails
If install_os_domU.sh fails to download the Xapi plugins zipball
correctly it ignores the error and continues the installation.
This could damage the hypervisor's filesystem, as it may delete
files or overwrite them with garbage.

Change-Id: I9f6dc31b977592e2818e37b2d310c2a5dc477364
Fixes: bug #1195640

diff --git a/tools/xen/functions b/tools/xen/functions
--- a/tools/xen/functions
+++ b/tools/xen/functions
@@ -41,10 +41,16 @@ function extract_remote_zipball {
     local EXTRACTED_FILES=$(mktemp -d)
 
     (
+	set -e
         wget -nv $ZIPBALL_URL -O $LOCAL_ZIPBALL --no-check-certificate
         unzip -q -o $LOCAL_ZIPBALL -d $EXTRACTED_FILES
         rm -f $LOCAL_ZIPBALL
     ) >&2
+
+    if [ $? -ne 0 ] ; then
+       echo "ERROR: failed to retrieve $ZIPBALL_URL"
+       exit 11
+    fi
 
     echo "$EXTRACTED_FILES"
 }
