Support patching projects/plugins
Add a patching mechanism right after cloning the
projects and fetching plugins, in order to allow the
user to supply patches. User will place his patches
under a "patches" directory under the devstack root
directory. The patch name will start with the name of
the project/plugin, and end with ".patch", and between
the user can put a string to identify the patch.

Change-Id: Ie28e1f8dda4ea138f08a3a8e3962bdfbe7ec2b06
Closes-Bug: #1606625

diff --git a/functions-common b/functions-common
--- a/functions-common
+++ b/functions-common
@@ -1852,6 +1852,29 @@ function plugin_override_defaults {
     done
 }
 
+# patch_plugins
+#
+# Apply any user defined patches for projects/plugins after cloning/fetching
+function patch_plugins {
+    local plugins="${DEVSTACK_PLUGINS}"
+    local plugin
+    for plugin in ${plugins//,/ }; do
+        local patch_path=$TOP_DIR/patches
+        local patch_filename="${plugin}*.patch"
+        echo "Checking patch for plugin $plugin in path $patch_path/$patch_filename..."
+	for P in $patch_path/$patch_filename; do
+            [ -f $P ] || continue
+            local dir=${GITDIR[$plugin]}
+            echo "Patch detected for plugin $plugin, filename $P, applying.."
+            if patch -p0 --dry-run -d $dir < $P &>/dev/null; then
+                patch -p0 -d $dir < $P
+            else
+                echo "Error: Failed applying patch $P"
+            fi
+        done
+    done
+}
+
 # run_plugins
 #
 # Run the devstack/plugin.sh in all the plugin directories. These are
