Add support for IPv6 tunnel endpoints
Currently, neutron tunnel endpoints must be IPv4 addresses,
i.e. $HOST_IP, although IPv6 endpoints are supported by most
drivers.

Create a TUNNEL_IP_VERSION variable to choose which host IP
to use, either HOST_IP or HOST_IPV6, and configure it in the
OVS and Linuxbridge agent driver files. Default is IPv4, but
the goal is to eventually setup the "IPv6-only" jobs to use
it to truly have only IPv6 addresses being used. It can be
over-ridden by specifying TUNNEL_ENDPOINT_IP accordingly.

This behaves similar to the SERVICE_IP_VERSION option, which
can either be set to 4 or 6, but not 4+6 - the tunnel overhead
should be consistent on all systems in order not to have MTU
issues.

Must set the ML2 overlay_ip_version config option to match
else agent tunnel sync RPC will not work.

Must set the OVN external_ids:ovn-encap-ip config option to
the correct address.

Added 'devstack-ipv6-all' job definition and verification role
that will set all services and tunnels to use IPv6 addresses.

Change-Id: I6034278dfc17b55d7863bc4db541bbdaa983a686

diff --git a/functions-common b/functions-common
--- a/functions-common
+++ b/functions-common
@@ -49,7 +49,7 @@ KILL_PATH="$(which kill)"
 STACK_ENV_VARS="BASE_SQL_CONN DATA_DIR DEST ENABLED_SERVICES HOST_IP \
     KEYSTONE_SERVICE_URI \
     LOGFILE OS_CACERT SERVICE_HOST STACK_USER TLS_IP \
-    HOST_IPV6 SERVICE_IP_VERSION"
+    HOST_IPV6 SERVICE_IP_VERSION TUNNEL_ENDPOINT_IP TUNNEL_IP_VERSION"
 
 
 # Saves significant environment variables to .stackenv for later use
@@ -756,30 +756,51 @@ function get_default_host_ip {
     local host_ip_iface=$3
     local host_ip=$4
     local af=$5
+    local scope="all"
 
-    # Search for an IP unless an explicit is set by ``HOST_IP`` environment variable
-    if [ -z "$host_ip" -o "$host_ip" == "dhcp" ]; then
-        host_ip=""
+    if [ -z "$host_ip_iface" ]; then
         # Find the interface used for the default route
-        host_ip_iface=${host_ip_iface:-$(ip -f $af route | awk '/default/ {print $5}' | head -1)}
+        host_ip_iface=$(ip -f $af route | awk '/default/ {print $5}' | head -1)
+        # If an interface was found, restrict addresses to global scope,
+        # which will eliminate things like loopback. This is to make sure
+        # SERVICE_HOST is not ::1 when SERVICE_IP_VERSION=6
+        if [ ! -z "$host_ip_iface" ]; then
+            scope="global"
+        fi
+    fi
+
+    # Search for an IP unless an explicit is set by ``HOST_IP`` environment
+    # variable. Try 5 times to account for IPv6 DAD.
+    if [ -z "$host_ip" -o "$host_ip" == "dhcp" ]; then
+        local count=0
         local host_ips
-        host_ips=$(LC_ALL=C ip -f $af addr show ${host_ip_iface} | sed /temporary/d |awk /$af'/ {split($2,parts,"/");  print parts[1]}')
         local ip
-        for ip in $host_ips; do
-            # Attempt to filter out IP addresses that are part of the fixed and
-            # floating range. Note that this method only works if the ``netaddr``
-            # python library is installed. If it is not installed, an error
-            # will be printed and the first IP from the interface will be used.
-            # If that is not correct set ``HOST_IP`` in ``localrc`` to the correct
-            # address.
-            if [[ "$af" == "inet6" ]]; then
-                host_ip=$ip
-                break;
+
+        host_ip=""
+        while [ "$host_ip" == "" ]; do
+            count=$((count+1))
+            if [ "$count" -gt 5 ]; then
+                die $LINENO "Host IP not found"
             fi
-            if ! (address_in_net $ip $fixed_range || address_in_net $ip $floating_range); then
-                host_ip=$ip
-                break;
-            fi
+
+            host_ips=$(LC_ALL=C ip -f $af addr show scope ${scope} ${host_ip_iface} | sed /temporary/d | awk /$af'/ {split($2,parts,"/");  print parts[1]}')
+            for ip in $host_ips; do
+                # Attempt to filter out IP addresses that are part of the fixed
+                # and floating range. Note that this method only works if the
+                # ``netaddr`` python library is installed. If it is not
+                # installed, an error will be printed and the first IP from the
+                # interface will be used. If that is not correct set
+                # ``HOST_IP`` in ``localrc`` to the correct address.
+                if [[ "$af" == "inet6" ]]; then
+                    host_ip=$ip
+                    break;
+                fi
+                if ! (address_in_net $ip $fixed_range || address_in_net $ip $floating_range); then
+                    host_ip=$ip
+                    break;
+                fi
+            done
+            sleep 2
         done
     fi
     echo $host_ip
