collect service failures even when not under screen
When not running under screen we end up potentially missing some
services not starting because we don't check that they actually
started and write out error logs. We can replicate the screen logic
here to get the same .failure files which are useful for the gate.

Change-Id: I4dc7b956024fb03f4db59b0a7654ae5cd12bd206
Closes-Bug: #1504118

diff --git a/functions-common b/functions-common
--- a/functions-common
+++ b/functions-common
@@ -1284,9 +1284,13 @@ function _run_process {
     # Run under ``setsid`` to force the process to become a session and group leader.
     # The pid saved can be used with pkill -g to get the entire process group.
     if [[ -n "$group" ]]; then
-        setsid sg $group "$command" & echo $! >$SERVICE_DIR/$SCREEN_NAME/$service.pid
+        setsid sg $group "$command" & \
+        echo $! >$SERVICE_DIR/$SCREEN_NAME/$service.pid; \
+        fg || echo "$service failed to start" | tee "$SERVICE_DIR/$SCREEN_NAME/${service}.failure"
     else
-        setsid $command & echo $! >$SERVICE_DIR/$SCREEN_NAME/$service.pid
+        setsid $command & \
+        echo $! >$SERVICE_DIR/$SCREEN_NAME/$service.pid; \
+        fg || echo "$service failed to start" | tee "$SERVICE_DIR/$SCREEN_NAME/${service}.failure"
     fi
 
     # Just silently exit this process
