Test
Change-Id: Ifd3570d5348f534d5c95349f421d71510ca21604

diff --git a/functions-common b/functions-common
--- a/functions-common
+++ b/functions-common
@@ -1298,7 +1298,7 @@ function _run_process {
     # Run under ``setsid`` to force the process to become a session and group leader.
     # The pid saved can be used with pkill -g to get the entire process group.
     if [[ -n "$group" ]]; then
-        setsid sg $group "$command" & echo $! >$SERVICE_DIR/$SCREEN_NAME/$service.pid
+        setsid sg $group "$command" & echo $(pgrep -P $(echo $!)|head -1) >$SERVICE_DIR/$SCREEN_NAME/$service.pid
     else
         setsid $command & echo $! >$SERVICE_DIR/$SCREEN_NAME/$service.pid
     fi
@@ -1410,7 +1410,11 @@ function screen_process {
     # Append the process to the screen rc file
     screen_rc "$name" "$command"
 
-    screen -S $SCREEN_NAME -p $name -X stuff "$command & echo \$! >$SERVICE_DIR/$SCREEN_NAME/${name}.pid; fg || echo \"$name failed to start\" | tee \"$SERVICE_DIR/$SCREEN_NAME/${name}.failure\"$NL"
+    if [[ -n "$group" ]]; then
+        screen -S $SCREEN_NAME -p $name -X stuff "$command & echo \$(pgrep -P $(echo $!)|head -1) >$SERVICE_DIR/$SCREEN_NAME/${name}.pid; fg || echo \"$name failed to start\" | tee \"$SERVICE_DIR/$SCREEN_NAME/${name}.failure\"$NL"
+    else
+        screen -S $SCREEN_NAME -p $name -X stuff "$command & echo \$! >$SERVICE_DIR/$SCREEN_NAME/${name}.pid; fg || echo \"$name failed to start\" | tee \"$SERVICE_DIR/$SCREEN_NAME/${name}.failure\"$NL"
+    fi
 }
 
 # Screen rc file builder
@@ -1460,6 +1464,32 @@ function screen_stop_service {
     fi
 }
 
+# Wait for a service to stop, wait up to 10 seconds because sometimes
+# a service takes a while to shutdown.
+function ensure_service_stopped {
+    local wait_for=33
+    local still_running=""
+    while [ $wait_for -gt 0 ]; do
+        still_running=""
+        if [[ -n "$1" ]] && ps uhww -p "$1"; then
+            still_running=$1
+        fi
+
+        if [[ -n "$still_running" ]]; then
+            sleep 0.3
+        else
+            break
+        fi
+        wait_for=$(($wait_for - 1))
+    done
+
+    if [[ -n "$still_running" ]]; then
+        echo "The service can't be shutdown during 10 seconds: $still_running"
+        return 1
+    fi
+    return 0
+}
+
 # Stop a service process
 # If a PID is available use it, kill the whole process group via TERM
 # If screen is being used kill the screen window; this will catch processes
@@ -1475,28 +1505,20 @@ function stop_process {
     if is_service_enabled $service; then
         # Kill via pid if we have one available
         if [[ -r $SERVICE_DIR/$SCREEN_NAME/$service.pid ]]; then
-            pkill -g $(cat $SERVICE_DIR/$SCREEN_NAME/$service.pid)
-            # oslo.service tends to stop actually shutting down
-            # reliably in between releases because someone believes it
-            # is dying too early due to some inflight work they
-            # have. This is a tension. It happens often enough we're
-            # going to just account for it in devstack and assume it
-            # doesn't work.
-            #
-            # Set OSLO_SERVICE_WORKS=True to skip this block
-            if [[ -z "$OSLO_SERVICE_WORKS" ]]; then
-                # TODO(danms): Remove this double-kill when we have
-                # this fixed in all services:
-                # https://bugs.launchpad.net/oslo-incubator/+bug/1446583
-                sleep 1
-                # /bin/true becakse pkill on a non existant process returns an error
-                pkill -g $(cat $SERVICE_DIR/$SCREEN_NAME/$service.pid) || /bin/true
-            fi
+            local service_pid=$(cat $SERVICE_DIR/$SCREEN_NAME/$service.pid)
+            ps auxww
+            pgrep -ag $service_pid
+            kill $service_pid
             rm $SERVICE_DIR/$SCREEN_NAME/$service.pid
         fi
         if [[ "$USE_SCREEN" = "True" ]]; then
             # Clean up the screen window
             screen_stop_service $service
+        fi
+        # Check the service again to ensure it is stopped
+        if ! ensure_service_stopped $service_pid; then
+            echo "Forcing shutdown of the service $service: PID=$service_pid"
+            pkill -SIGKILL -g $service_pid
         fi
     fi
 }
