[WIP] Add retries to image download
Image download could fail for network issues,
let's retry if it fails with network error.

Related-Bug: #2045725
Change-Id: Id8bff85325246bfc158a7da87c739e6563a63c68

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -139,10 +139,18 @@ function upload_image {
     if [[ $image_url != file* ]]; then
         # Downloads the image (uec ami+akistyle), then extracts it.
         if [[ ! -f $FILES/$image_fname || "$(stat -c "%s" $FILES/$image_fname)" = "0" ]]; then
-            wget --progress=dot:giga -c $image_url -O $FILES/$image_fname
-            if [[ $? -ne 0 ]]; then
-                echo "Not found: $image_url"
-                return
+            wget --progress=dot:giga -c $image_url -O $FILES/$image_fname || rc=$?
+            if [[ $rc -ne 0 ]]; then
+                echo "Download failure: $image_url, retrying 2nd attempt"
+                sleep 3 && wget --progress=dot:giga -c $image_url -O $FILES/$image_fname || rc=$?
+                if [[ $rc -ne 0 ]]; then
+                    echo "Download failure: $image_url, retrying 3rd attempt"
+                    sleep 5 && wget --progress=dot:giga -c $image_url -O $FILES/$image_fname
+                    if [[ $? -ne 0 ]]; then
+                        echo "Not found: $image_url, return"
+                        return
+                    fi
+                fi
             fi
         fi
         image="$FILES/${image_fname}"
