Ensure pip_install failure is fatal
If pip_install fails it is sure that dependencies will be missing,
leading to (often) bizarre looking errors much later on.  Thus such a
failure should be fatal to the ongoing operation of devstack.

Change-Id: I0f4a2988e0601812ca373cc3bffc8c7dc3549695

diff --git a/functions-common b/functions-common
--- a/functions-common
+++ b/functions-common
@@ -1128,6 +1128,10 @@ function pip_install {
         $CMD_PIP install --build=${pip_build_tmp} \
         $PIP_MIRROR_OPT $@ \
         && $SUDO_PIP rm -rf ${pip_build_tmp}
+
+    if [[ $? -ne 0 ]]; then
+	die $LINENO "pip install failed, can not continue"
+    fi
 }
 
 
