Make yum install ignore missing packages if architecture is ppc64
There's a few packages missing in ppc64 architecture.
The latest patch https://review.openstack.org/#/c/77067
Broken the devstack in ppc64 due the check if there's
missed packages.
This patch check if the architecture is ppc64 if so
uses the old way, just with yum install -y.
Otherwise, it will use the new check.

Change-Id: I3fd4aeaf183b8def787ba677f8941bf52e5d1b53

diff --git a/functions-common b/functions-common
--- a/functions-common
+++ b/functions-common
@@ -939,22 +939,31 @@ function yum_install {
     local sudo="sudo"
     [[ "$(id -u)" = "0" ]] && sudo="env"
 
-    # The manual check for missing packages is because yum -y assumes
-    # missing packages are OK.  See
-    # https://bugzilla.redhat.com/show_bug.cgi?id=965567
-    $sudo http_proxy=$http_proxy https_proxy=$https_proxy \
-        no_proxy=$no_proxy \
-        yum install -y "$@" 2>&1 | \
-        awk '
-            BEGIN { fail=0 }
-            /No package/ { fail=1 }
-            { print }
-            END { exit fail }' || \
-                die $LINENO "Missing packages detected"
+    # PowerPC have some missing packages like mongo-db, we
+    # don't want to kill the yum if it's running in
+    # ppc64 architecture
+    if is_arch "ppc64" then
+        $sudo http_proxy=$http_proxy https_proxy=$https_proxy \
+            no_proxy=$no_proxy \
+            yum install -y "$@"
+    else
+        # The manual check for missing packages is because yum -y assumes
+        # missing packages are OK.  See
+        # https://bugzilla.redhat.com/show_bug.cgi?id=965567
+        $sudo http_proxy=$http_proxy https_proxy=$https_proxy \
+            no_proxy=$no_proxy \
+            yum install -y "$@" 2>&1 | \
+            awk '
+                BEGIN { fail=0 }
+                /No package/ { fail=1 }
+                { print }
+                END { exit fail }' || \
+                    die $LINENO "Missing packages detected"
 
-    # also ensure we catch a yum failure
-    if [[ ${PIPESTATUS[0]} != 0 ]]; then
-        die $LINENO "Yum install failure"
+        # also ensure we catch a yum failure
+        if [[ ${PIPESTATUS[0]} != 0 ]]; then
+            die $LINENO "Yum install failure"
+        fi
     fi
 }
 
