Make multiple attempts to pull image
Often times fetching Fedora image in FIPS jobs fails due to
"GnuTLS: One of the involved algorithms has insufficient security level."

This occurs when request to pull image is redirected to a mirror that's
incompatible with FIPS enabled system.

Making multiple attempts to pull images could provide better chance of
pulling images from different mirrors and avoid failure of the job.
This will also save a few rechecks.

Change-Id: I7163aea4d121cb27620e4f2a083a543abfc286bf

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -138,13 +138,21 @@ function upload_image {
     image_fname=`basename "$image_url"`
     if [[ $image_url != file* ]]; then
         # Downloads the image (uec ami+akistyle), then extracts it.
-        if [[ ! -f $FILES/$image_fname || "$(stat -c "%s" $FILES/$image_fname)" = "0" ]]; then
-            wget --progress=dot:giga -c $image_url -O $FILES/$image_fname
-            if [[ $? -ne 0 ]]; then
-                echo "Not found: $image_url"
-                return
-            fi
-        fi
+        max_attempts=10
+        for i in $( eval echo {0..$max_attempts} )
+        do
+            if [[ ! -f $FILES/$image_fname || "$(stat -c "%s" $FILES/$image_fname)" = "0" ]]; then
+                wget --progress=dot:giga -c $image_url -O $FILES/$image_fname
+                if [[ $? -ne 0 ]]; then
+                    echo "Not found: $image_url"
+                    echo $i
+                    if [[ "$i" -eq "$max_attempts" ]]; then
+                        return
+                    fi  
+                    echo "Retrying..."
+                fi  
+            fi  
+        done
         image="$FILES/${image_fname}"
     else
         # File based URL (RFC 1738): ``file://host/path``
