Add err()/err_if_not_set()
* err() and err_if_not_set() do error-like reporting without aborting the script
* die_if_not_set() now properly dies

Change-Id: I38b88112415a3c07e35bbc2dc65ad839c4d63fce

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -57,15 +57,12 @@ function cp_it {
 # die $LINENO "message"
 function die() {
     local exitcode=$?
+    set +o xtrace
+    local line=$1; shift
     if [ $exitcode == 0 ]; then
         exitcode=1
     fi
-    set +o xtrace
-    local msg="[ERROR] $0:$1 $2"
-    echo $msg 1>&2;
-    if [[ -n ${SCREEN_LOGDIR} ]]; then
-        echo $msg >> "${SCREEN_LOGDIR}/error.log"
-    fi
+    err $line "$*"
     exit $exitcode
 }
 
@@ -75,14 +72,49 @@ function die() {
 # NOTE: env-var is the variable name without a '$'
 # die_if_not_set $LINENO env-var "message"
 function die_if_not_set() {
-    (
-        local exitcode=$?
-        set +o xtrace
-        local evar=$2; shift
-        if ! is_set $evar || [ $exitcode != 0 ]; then
-            die $@
-        fi
-    )
+    local exitcode=$?
+    FXTRACE=$(set +o | grep xtrace)
+    set +o xtrace
+    local line=$1; shift
+    local evar=$1; shift
+    if ! is_set $evar || [ $exitcode != 0 ]; then
+        die $line "$*"
+    fi
+    $FXTRACE
+}
+
+
+# Prints line number and "message" in error format
+# err $LINENO "message"
+function err() {
+    local exitcode=$?
+    errXTRACE=$(set +o | grep xtrace)
+    set +o xtrace
+    local msg="[ERROR] $0:$1 $2"
+    echo $msg 1>&2;
+    if [[ -n ${SCREEN_LOGDIR} ]]; then
+        echo $msg >> "${SCREEN_LOGDIR}/error.log"
+    fi
+    $errXTRACE
+    return $exitcode
+}
+
+
+# Checks an environment variable is not set or has length 0 OR if the
+# exit code is non-zero and prints "message"
+# NOTE: env-var is the variable name without a '$'
+# err_if_not_set $LINENO env-var "message"
+function err_if_not_set() {
+    local exitcode=$?
+    errinsXTRACE=$(set +o | grep xtrace)
+    set +o xtrace
+    local line=$1; shift
+    local evar=$1; shift
+    if ! is_set $evar || [ $exitcode != 0 ]; then
+        err $line "$*"
+    fi
+    $errinsXTRACE
+    return $exitcode
 }
 
 
