Add a single retry in to apt-get update
We are regularly seeing apt-get update fail in the gate, this may be due
to transient issues with the network/mirror. To work around this add a
single retry in.

Change-Id: I14b2ee69a5c39dacdb9c30c920cbd376f2d57831
Related-Bug: # 1286635

diff --git a/functions-common b/functions-common
--- a/functions-common
+++ b/functions-common
@@ -885,9 +885,13 @@ function install_package {
     local xtrace=$(set +o | grep xtrace)
     set +o xtrace
     if is_ubuntu; then
-        # if there are transient errors pulling the updates, that's fine. It may
-        # be secondary repositories that we don't really care about.
-        [[ "$NO_UPDATE_REPOS" = "True" ]] || apt_get update || /bin/true
+        # if there are transient errors pulling the updates try again, and
+        # if that fails. continue since it may be a secondary repository
+        # that we don't really care about.
+        if ! ([[ "$NO_UPDATE_REPOS" = "True" ]] || apt_get update ) ; then
+          sleep 10
+          [[ "$NO_UPDATE_REPOS" = "True" ]] || apt_get update || /bin/true
+        fi
         NO_UPDATE_REPOS=True
 
         $xtrace
