Build retry loop for screen sessions
There is a timing window where we might lose the commands being
stuffed into screen because bash is spawning. In those cases, loop
around and try building screen sessions again.

Change-Id: I49247de06bbd59424cb10fb9a8db145907be5138
Related-Bug: #1331274

diff --git a/functions-common b/functions-common
--- a/functions-common
+++ b/functions-common
@@ -1061,41 +1061,57 @@ function run_process {
 # Helper to launch a service in a named screen
 # screen_it service "command-line"
 function screen_it {
+    local service=$1
+    local cmd=$2
     SCREEN_NAME=${SCREEN_NAME:-stack}
     SERVICE_DIR=${SERVICE_DIR:-${DEST}/status}
     USE_SCREEN=$(trueorfalse True $USE_SCREEN)
+    local pid="$SERVICE_DIR/$SCREEN_NAME/$service.pid"
 
     if is_service_enabled $1; then
         # Append the service to the screen rc file
-        screen_rc "$1" "$2"
+        screen_rc "$service" "$cmd"
 
         if [[ "$USE_SCREEN" = "True" ]]; then
-            screen -S $SCREEN_NAME -X screen -t $1
+            screen -S $SCREEN_NAME -X screen -t $service
 
-            if [[ -n ${SCREEN_LOGDIR} ]]; then
-                screen -S $SCREEN_NAME -p $1 -X logfile ${SCREEN_LOGDIR}/screen-${1}.${CURRENT_LOG_TIME}.log
-                screen -S $SCREEN_NAME -p $1 -X log on
-                ln -sf ${SCREEN_LOGDIR}/screen-${1}.${CURRENT_LOG_TIME}.log ${SCREEN_LOGDIR}/screen-${1}.log
-            fi
+            local screen_tries=0
+            while [ "$screen_tries" -lt 10 ]; do
+                if [[ -n ${SCREEN_LOGDIR} ]]; then
+                    local logfile=${SCREEN_LOGDIR}/screen-${service}.${CURRENT_LOG_TIME}.log
+                    local shortlog=${SCREEN_LOGDIR}/screen-${service}.log
+                    # this whole dance is done because of slow nodes
+                    screen -S $SCREEN_NAME -p $service -X logfile ${logfile} 1
+                    ln -sf ${logfile} ${shortlog}
+                fi
 
-            # sleep to allow bash to be ready to be send the command - we are
-            # creating a new window in screen and then sends characters, so if
-            # bash isn't running by the time we send the command, nothing happens
-            sleep 3
-
-            NL=`echo -ne '\015'`
-            # This fun command does the following:
-            # - the passed server command is backgrounded
-            # - the pid of the background process is saved in the usual place
-            # - the server process is brought back to the foreground
-            # - if the server process exits prematurely the fg command errors
-            #   and a message is written to stdout and the service failure file
-            # The pid saved can be used in screen_stop() as a process group
-            # id to kill off all child processes
-            screen -S $SCREEN_NAME -p $1 -X stuff "$2 & echo \$! >$SERVICE_DIR/$SCREEN_NAME/$1.pid; fg || echo \"$1 failed to start\" | tee \"$SERVICE_DIR/$SCREEN_NAME/$1.failure\"$NL"
+                NL=`echo -ne '\015'`
+                # This fun command does the following:
+                # - the passed server command is backgrounded
+                # - the pid of the background process is saved in the usual place
+                # - the server process is brought back to the foreground
+                # - if the server process exits prematurely the fg command errors
+                #   and a message is written to stdout and the service failure file
+                # The pid saved can be used in screen_stop() as a process group
+                # id to kill off all child processes
+                local failure="$SERVICE_DIR/$SCREEN_NAME/$service.failure"
+                screen -S $SCREEN_NAME -p $service -X stuff "$cmd & echo \$! >$pid; fg || echo \"$servic failed to start\" | tee \"$failure\"$NL"
+                if [ ! -e "$pid" && ! -e "$failure" ]; then
+                    if [[ "$screen_tries" -eq 9 ]]; then
+                        echo "Failed to create screen session for $service using $cmd"
+                        exit 1
+                    fi
+                    echo "Attempt $screen_tries: failed to run $cmd"
+                    screen_tries=$[screen_tries + 1]
+                    sleep 1
+                else
+                    # success, we're done
+                    screen_tries=10
+                fi
+            done
         else
             # Spawn directly without screen
-            run_process "$1" "$2" >$SERVICE_DIR/$SCREEN_NAME/$1.pid
+            run_process "$service" "$cmd" >$pid
         fi
     fi
 }
