Ensure die is called if git fetch/checkout fails
This patch ensures that if git fetch or checkout fails that devstack
stops running and prevents it from continuing on so it is ensured the
intended code is running.

Closes-bug: #1283173
Change-Id: I16e37214726c227fa0b7372b2b868c052c2aa23b

diff --git a/functions-common b/functions-common
--- a/functions-common
+++ b/functions-common
@@ -502,6 +502,9 @@ function git_clone {
         fi
         cd $GIT_DEST
         git fetch $GIT_REMOTE $GIT_REF && git checkout FETCH_HEAD
+        if [ $? -ne 0 ]; then
+            die $LINENO "git fetch or checkout failed"
+        fi
     else
         # do a full clone only if the directory doesn't exist
         if [[ ! -d $GIT_DEST ]]; then
