Optimize install_package function when executing nominal flow.
Change-Id: Ib8d8a98f9e47c6f1332d8886366cce33f2891cab
Depends-On: I4a536abefa7824ac6d42e7bbbf1079d9cc055984
Closes-Bug: #1518544

diff --git a/functions-common b/functions-common
--- a/functions-common
+++ b/functions-common
@@ -1147,28 +1147,39 @@ function get_plugin_packages {
 
 # Distro-agnostic package installer
 # Uses globals ``NO_UPDATE_REPOS``, ``REPOS_UPDATED``, ``RETRY_UPDATE``
-# install_package package [package ...]
+# update_package_repo
 function update_package_repo {
-    NO_UPDATE_REPOS=${NO_UPDATE_REPOS:-False}
     REPOS_UPDATED=${REPOS_UPDATED:-False}
     RETRY_UPDATE=${RETRY_UPDATE:-False}
 
-    if [[ "$NO_UPDATE_REPOS" = "True" ]]; then
-        return 0
+    if [[ "$REPOS_UPDATED" != "True" || "$RETRY_UPDATE" = "True" ]]; then
+        retry_update_package_repo
+    fi
+}
+
+# Distro-agnostic package installer
+# Uses globals ``NO_UPDATE_REPOS``, ``REPOS_UPDATED``
+# retry_update_package_repo
+function retry_update_package_repo {
+    NO_UPDATE_REPOS=${NO_UPDATE_REPOS:-False}
+
+    if [[ "$NO_UPDATE_REPOS" != "True" ]]; then
+        if is_ubuntu; then
+            local xtrace
+            xtrace=$(set +o | grep xtrace)
+            set +o xtrace
+
+            # If there are transient errors pulling the updates, that's fine.
+            # It may be secondary repositories that we don't really care about.
+            apt_get update || true
+            local RESULT=$?
+
+            REPOS_UPDATED=True
+            $xtrace
+        fi
     fi
 
-    if is_ubuntu; then
-        local xtrace
-        xtrace=$(set +o | grep xtrace)
-        set +o xtrace
-        if [[ "$REPOS_UPDATED" != "True" || "$RETRY_UPDATE" = "True" ]]; then
-            # if there are transient errors pulling the updates, that's fine.
-            # It may be secondary repositories that we don't really care about.
-            apt_get update  || /bin/true
-            REPOS_UPDATED=True
-        fi
-        $xtrace
-    fi
+    return ${RESULT:-0}
 }
 
 function real_install_package {
@@ -1186,8 +1197,25 @@ function real_install_package {
 # Distro-agnostic package installer
 # install_package package [package ...]
 function install_package {
-    update_package_repo
-    real_install_package $@ || RETRY_UPDATE=True update_package_repo && real_install_package $@
+    # I fill lucky: update pakages index only after that installation has failed
+    if real_install_package "$@"; then
+        # Package installed at first attempt!
+        return 0
+    else
+        # Retry installing after updating pakcage index
+        # If there are transient errors pulling the updates, that's fine.
+        # It may be secondary repositories that we don't really care about.
+
+        retry_update_package_repo
+        if real_install_package "$@"; then
+            # Package installed at second attempt
+            return 0
+        fi
+    fi
+
+    # Something went wrong.
+    echo "Unable to install package(s):" "$@"
+    return 1
 }
 
 # Distro-agnostic function to tell if a package is installed
