Ensure images downloaded from a previous stack are fully downloaded
Currently, stack.sh does not check if an image file downloaded from
a previous stack.sh execution is fully downloaded before using it.
This patch updates the wget command to use the --timestamping
option which will re-download a file if the server modified date is
more recent than the local file as well as when the server file
size differs from the local file.

Change-Id: I343248f7d5e8bda19c93cb19092b5459b28244b0
Closes-Bug: #1403492

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -44,12 +44,10 @@ function upload_image {
     image_fname=`basename "$image_url"`
     if [[ $image_url != file* ]]; then
         # Downloads the image (uec ami+akistyle), then extracts it.
-        if [[ ! -f $FILES/$image_fname || "$(stat -c "%s" $FILES/$image_fname)" = "0" ]]; then
-            wget --progress=dot:giga -c $image_url -O $FILES/$image_fname
-            if [[ $? -ne 0 ]]; then
-                echo "Not found: $image_url"
-                return
-            fi
+        wget --timestamping --progress=dot:giga -c $image_url -P $FILES
+        if [[ $? -ne 0 ]]; then
+            echo "Not found: $image_url"
+            return
         fi
         image="$FILES/${image_fname}"
     else
