Make wait_for_service more robust by checking HTTP response
wait_for_service just checked to see if the remote service
was started, not that it was returning data. This caused
problems when the service was behind a proxy because the
proxy would respond quickly but the service may not have
fully started.

Wait for a non-503 HTTP response code and non-7 exit code
(connection error) from curl

The \EOF form is used so the heredoc isn't evaluated before
the call is made. Otherwise it would be evaluated just once
so the loop is not valuable.

Variables needed to be exported in order to be available when
this form is used.

Change-Id: I059a12b1b920f703f28aca0e2f352714118dee97

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -381,12 +381,29 @@ CURL_GET="${CURL_GET:-curl -g}"
 
 # Wait for an HTTP server to start answering requests
 # wait_for_service timeout url
+#
+# If the service we want is behind a proxy, the proxy may be available
+# before the service. Compliant proxies will return a 503 in this case
+# Loop until we get something else.
+# Also check for the case where there is no proxy and the service just
+# hasn't started yet. curl returns 7 for Failed to connect to host.
 function wait_for_service {
     local timeout=$1
-    local url=$2
+    export wait_for_url=$2
+    export CURL_GET
+    local rval=0
     time_start "wait_for_service"
-    timeout $timeout sh -c "while ! $CURL_GET -k --noproxy '*' -s $url >/dev/null; do sleep 1; done"
+    # The form \EOF is used here otherwise the variables are expanded
+    # before running heredoc and it only gets executed once.
+    # export is needed to pass in the variables we need
+    timeout $timeout bash -x <<\EOF
+        while [[ $(${CURL_GET} -k --noproxy '*' -s -o /dev/null -w '%{http_code}' ${wait_for_url}) = 503 || $? -eq 7 ]]; do
+            sleep 1
+        done
+EOF
+    rval=$?
     time_stop "wait_for_service"
+    return $rval
 }
 
 
