TESTING: Add secondary mirror for ubuntu
We are seeing occasional rackspace apt mirror failures, to work around
this in case of a failure swap mirror with anl.gov.
Use anl.gov because it is in the US, has a 10GB network and is usually
up to date.

This workaround is needed because apt-get doesn't know how to gracefully
recover if the primary source vanishes.

This is for testing only a proper solution belongs in devstack-gate.
devstack-gate can run an apt-get update before entering devstack and run
this action if apt-get update has issues.

Testing what happens with a mirror that will return 404 errors.

Change-Id: I5e9fc1edab8f6531285b3ea02641aec9470cad4d

diff --git a/functions-common b/functions-common
--- a/functions-common
+++ b/functions-common
@@ -857,6 +857,21 @@ function apt_get {
         http_proxy=$http_proxy https_proxy=$https_proxy \
         no_proxy=$no_proxy \
         apt-get --option "Dpkg::Options::=--force-confold" --assume-yes "$@"
+    RESULT=$?
+    if [ $RESULT -ne 0 ]; then
+        # if apt-get failed the mirror may be bad, replace apt source with
+        # mirror.anl.gov run update and try again
+        sudo sed -i 's,^\(deb[^ ]*\) http://[^ ]\+ ,\1 http://mirror.anl.gov/pub/ubuntu/ ,' /etc/apt/sources.list
+        $sudo DEBIAN_FRONTEND=noninteractive \
+            http_proxy=$http_proxy https_proxy=$https_proxy \
+            no_proxy=$no_proxy \
+            apt-get --option "Dpkg::Options::=--force-confold" --assume-yes update
+        $sudo DEBIAN_FRONTEND=noninteractive \
+            http_proxy=$http_proxy https_proxy=$https_proxy \
+            no_proxy=$no_proxy \
+            apt-get --option "Dpkg::Options::=--force-confold" --assume-yes "$@"
+    fi
+
 }
 
 # get_packages() collects a list of package names of any type from the
@@ -996,6 +1011,8 @@ function update_package_repo {
             # if there are transient errors pulling the updates, that's fine.
             # It may be secondary repositories that we don't really care about.
             apt_get update  || /bin/true
+            # now change the mirror ip address to something bogus and re-update
+            sudo sh -c 'echo 192.237.219.31 mirror.rackspace.com >> /etc/hosts'
             REPOS_UPDATED=True
         fi
         $xtrace
