collect service failures even when not under screen
When not running under screen we end up potentially missing some
services not starting because we don't check that they actually
started and write out error logs.

We mitigate this by ensuring that pids we believe should be running, are at
the end of the run.  This does potentially have a race on pid wrapping, but
it is a 95% solution that will help us identify some breaks.

Change-Id: I4dc7b956024fb03f4db59b0a7654ae5cd12bd206
Closes-Bug: #1504118

diff --git a/functions-common b/functions-common
--- a/functions-common
+++ b/functions-common
@@ -1284,9 +1284,11 @@ function _run_process {
     # Run under ``setsid`` to force the process to become a session and group leader.
     # The pid saved can be used with pkill -g to get the entire process group.
     if [[ -n "$group" ]]; then
-        setsid sg $group "$command" & echo $! >$SERVICE_DIR/$SCREEN_NAME/$service.pid
+        setsid sg $group "$command" & \
+        echo $! >$SERVICE_DIR/$SCREEN_NAME/$service.pid
     else
-        setsid $command & echo $! >$SERVICE_DIR/$SCREEN_NAME/$service.pid
+        setsid $command & \
+        echo $! >$SERVICE_DIR/$SCREEN_NAME/$service.pid;
     fi
 
     # Just silently exit this process
@@ -1493,6 +1495,7 @@ function stop_process {
 function service_check {
     local service
     local failures
+    local pids
     SCREEN_NAME=${SCREEN_NAME:-stack}
     SERVICE_DIR=${SERVICE_DIR:-${DEST}/status}
 
@@ -1514,6 +1517,21 @@ function service_check {
 
     if [ -n "$failures" ]; then
         die $LINENO "More details about the above errors can be found with screen, with ./rejoin-stack.sh"
+    fi
+
+    pids=`ls "$SERVICE_DIR/$SCREEN_NAME"/*.pid 2>/dev/null || /bin/true`
+    local missing_pids
+    local pid
+    for pidfile in $pids; do
+        pid=$(cat $pidfile)
+        if ! ps -p $pid; then
+            echo "Error: Service $(basename $pidfile) not found"
+            missing_pids+="$(basename $pidfile):$pid "
+        fi
+    done
+
+    if [ -n "$missing_pids" ]; then
+        die $LINENO "Some services don't seem to be running: $missing_pids"
     fi
 }
 
