Ignore second enable_plugin request
There are situations when DEVSTACK_PLUGINS variable is set
while _DEVSTACK_STACKRC is not. In this case plugin will be enabled twice.
Instead of failing here, we ignore second attempt and show warning.

Change-Id: I940e732278257cd759bd9bc4744c1fc1267d06f5

diff --git a/functions-common b/functions-common
--- a/functions-common
+++ b/functions-common
@@ -23,7 +23,7 @@
 # - ``ENABLED_SERVICES``
 # - ``ERROR_ON_CLONE``
 # - ``FILES``
-# - ``OFFLINE``
+# - ``OFFLINE``Instead of failing here, we ignore second attempt and show warning.
 # - ``RECLONE``
 # - ``REQUIREMENTS_DIR``
 # - ``STACK_USER``
@@ -1775,13 +1775,17 @@ function enable_plugin {
     local name=$1
     local url=$2
     local branch=${3:-master}
-    if [[ ",${DEVSTACK_PLUGINS}," =~ ,${name}, ]]; then
-        die $LINENO "Plugin attempted to be enabled twice: ${name} ${url} ${branch}"
+    # NOTE(vsaienko) there are situations when DEVSTACK_PLUGINS variable is set,
+    # while _DEVSTACK_STACKRC is not. In this case plugin will be enabled twice.
+    # Instead of failing here, we ignore second attempt.
+    # Do not print anything avoid setting output to variable for example:
+    # https://github.com/openstack-dev/grenade/blob/6d3e6c/inc/upgrade#L38
+    if ! [[ ",${DEVSTACK_PLUGINS}," =~ ,${name}, ]]; then
+        DEVSTACK_PLUGINS+=",$name"
+        GITREPO[$name]=$url
+        GITDIR[$name]=$DEST/$name
+        GITBRANCH[$name]=$branch
     fi
-    DEVSTACK_PLUGINS+=",$name"
-    GITREPO[$name]=$url
-    GITDIR[$name]=$DEST/$name
-    GITBRANCH[$name]=$branch
 }
 
 # fetch_plugins
