Replace peakmem_tracker by memory_tracker
These both run the same service under different names. The old name has
been deprecated since Pike, so we switch to running under the new name
now and drop the old one. Also fail when the old service is still
configured, otherwise consumer will never notice.

Change-Id: I583caf3f36a8ff41d7d4106dabc6c5f24243085e

diff --git a/lib/dstat b/lib/dstat
--- a/lib/dstat
+++ b/lib/dstat
@@ -26,10 +26,11 @@ function start_dstat {
     # to your localrc
     run_process memory_tracker "$TOP_DIR/tools/memory_tracker.sh" "" "root"
 
-    # remove support for the old name when it's no longer used (sometime in Queens)
+    # TODO(jh): Fail when using the old service name otherwise consumers will
+    # never notice that is has been removed. Drop this again before ussuri.
     if is_service_enabled peakmem_tracker; then
         deprecated "Use of peakmem_tracker in devstack is deprecated, use memory_tracker instead"
-        run_process peakmem_tracker "$TOP_DIR/tools/memory_tracker.sh" "" "root"
+        exit 1
     fi
 }
 
