Initialize metadata definitions catalog
This patch copies all files from /etc/metadefs to
/etc/glance/metadefs and calls glance-manage db_load_metadefs
after successful database migration. This covers whole
process of initializing the metadata catalog.

Change-Id: I2ffd19bf543708b42229ef78dd17ee317f58e6ad
Implements: blueprint glance-metadata-definitions-support

diff --git a/lib/glance b/lib/glance
--- a/lib/glance
+++ b/lib/glance
@@ -34,6 +34,7 @@ GLANCE_IMAGE_DIR=${GLANCE_IMAGE_DIR:=$DATA_DIR/glance/images}
 GLANCE_AUTH_CACHE_DIR=${GLANCE_AUTH_CACHE_DIR:-/var/cache/glance}
 
 GLANCE_CONF_DIR=${GLANCE_CONF_DIR:-/etc/glance}
+GLANCE_METADEF_DIR=$GLANCE_CONF_DIR/metadefs
 GLANCE_REGISTRY_CONF=$GLANCE_CONF_DIR/glance-registry.conf
 GLANCE_API_CONF=$GLANCE_CONF_DIR/glance-api.conf
 GLANCE_REGISTRY_PASTE_INI=$GLANCE_CONF_DIR/glance-registry-paste.ini
@@ -78,8 +79,10 @@ function cleanup_glance {
 function configure_glance {
     if [[ ! -d $GLANCE_CONF_DIR ]]; then
         sudo mkdir -p $GLANCE_CONF_DIR
+        sudo mkdir -p $GLANCE_METADEF_DIR
     fi
     sudo chown $STACK_USER $GLANCE_CONF_DIR
+    sudo chown $STACK_USER $GLANCE_METADEF_DIR
 
     # Copy over our glance configurations and update them
     cp $GLANCE_DIR/etc/glance-registry.conf $GLANCE_REGISTRY_CONF
@@ -157,6 +160,13 @@ function configure_glance {
 
     cp -p $GLANCE_DIR/etc/policy.json $GLANCE_POLICY_JSON
     cp -p $GLANCE_DIR/etc/schema-image.json $GLANCE_SCHEMA_JSON
+
+    # This try catch block will be removed after seeding part merge
+    {
+        cp -p $GLANCE_DIR/etc/metadefs/*.json $GLANCE_METADEF_DIR
+    } || {
+        echo "Failed to copy metadata definition files. Continuing..."
+    }
 }
 
 # create_glance_accounts() - Set up common required glance accounts
@@ -220,6 +230,13 @@ function init_glance {
 
     # Migrate glance database
     $GLANCE_BIN_DIR/glance-manage db_sync
+
+    # Load metadata definitions
+    {
+        $GLANCE_BIN_DIR/glance-manage db_load_metadefs
+    } || {
+        echo "Failed to load metadata definitions. Continuing..."
+    }
 
     create_glance_cache_dir
 }
