Add the ability to install/enable Heat plugins
Adds the $ENABLE_HEAT_PLUGINS variable, which should be a list of
the names of the plugins the user wishes to install.

Change-Id: I2ba90002a8fad1cdce6543c89dc37c5912fe133e

diff --git a/lib/heat b/lib/heat
--- a/lib/heat
+++ b/lib/heat
@@ -169,6 +169,34 @@ function configure_heat {
     # copy the default templates
     cp $HEAT_DIR/etc/heat/templates/* $HEAT_TEMPLATES_DIR/
 
+    # Enable heat plugins.  The symlink nonsense is necessary because
+    # when plugins are installed in "developer mode", the final
+    # component of their target directory is always "resources",
+    # which confuses Heat's plugin loader into believing that all
+    # plugins are named "resources", and therefore are all the same
+    # plugin; so it will only load one of them.  Linking them all
+    # to a common location with unique names avoids that type of
+    # collision, while still allowing the plugins to be edited in-tree.
+    err_count=0
+    HEAT_PLUGIN_DIR=$DATA_DIR/heat/plugins
+    if [ -n "$ENABLE_HEAT_PLUGINS" ]; then
+        mkdir -p $HEAT_PLUGIN_DIR
+        # Clean up cruft from any previous runs
+        rm -f $HEAT_PLUGIN_DIR/*
+        iniset $HEAT_CONF DEFAULT plugin_dirs $HEAT_PLUGIN_DIR
+    fi
+
+    for HEAT_PLUGIN in $ENABLE_HEAT_PLUGINS; do
+        if [ -d $HEAT_DIR/contrib/$HEAT_PLUGIN ]; then
+            setup_package $HEAT_DIR/contrib/$HEAT_PLUGIN -e
+            ln -s $HEAT_DIR/contrib/$HEAT_PLUGIN/$HEAT_PLUGIN/resources $HEAT_PLUGIN_DIR/$HEAT_PLUGIN
+        else
+            : clear retval on the test so that we can roll up errors
+            err $LINENO "Requested Heat plugin(${HEAT_PLUGIN}) not found."
+            let err_count="$err_count + 1"
+        fi
+    done
+    [ ${err_count:-0} -eq 0 ] || die $LINENO "$err_count of the requested Heat plugins could be installed."
 }
 
 # init_heat() - Initialize database
