Add support for building ISO for deploy ramdisk
This commit adds support for building and uploading
an ISO image for deploy ramdisk.  This is used by
some drivers in Ironic today. A new variable
IRONIC_DEPLOY_ISO_REQUIRED=true can be set in localrc
to create and upload ISO image for the deploy ramdisk.

Closes-Bug: 1510914
Change-Id: I27ab9ab03f8af41cc3906f1ede9b85e5127c766f

diff --git a/lib/ironic b/lib/ironic
--- a/lib/ironic
+++ b/lib/ironic
@@ -95,8 +95,10 @@ IRONIC_BUILD_DEPLOY_RAMDISK=$(trueorfalse True IRONIC_BUILD_DEPLOY_RAMDISK)
 # (The value must be a absolute path)
 IRONIC_DEPLOY_RAMDISK=${IRONIC_DEPLOY_RAMDISK:-}
 IRONIC_DEPLOY_KERNEL=${IRONIC_DEPLOY_KERNEL:-}
+IRONIC_DEPLOY_ISO=${IRONIC_DEPLOY_ISO:-}
 IRONIC_DEPLOY_ELEMENT=${IRONIC_DEPLOY_ELEMENT:-deploy-ironic}
 IRONIC_IPA_RAMDISK_DISTRO=${IRONIC_IPA_RAMDISK_DISTRO:-coreos}
+IRONIC_DEPLOY_ISO_REQUIRED=$(trueorfalse False IRONIC_DEPLOY_ISO_REQUIRED)
 
 IRONIC_AGENT_KERNEL_URL=${IRONIC_AGENT_KERNEL_URL:-http://tarballs.openstack.org/ironic-python-agent/coreos/files/coreos_production_pxe.vmlinuz}
 IRONIC_AGENT_RAMDISK_URL=${IRONIC_AGENT_RAMDISK_URL:-http://tarballs.openstack.org/ironic-python-agent/coreos/files/coreos_production_pxe_image-oem.cpio.gz}
@@ -175,6 +177,11 @@ function is_deployed_by_agent {
 
 function is_deployed_with_ipa_ramdisk {
     is_deployed_by_agent || [[ "$IRONIC_DEPLOY_DRIVER_ISCSI_WITH_IPA" == "True" ]] && return 0
+    return 1
+}
+
+function is_deploy_iso_required {
+    [[ "$IRONIC_DEPLOY_ISO_REQUIRED" == "True" ]] && return 0
     return 1
 }
 
@@ -740,10 +747,11 @@ function configure_ironic_auxiliary {
 function build_ipa_ramdisk {
     local kernel_path=$1
     local ramdisk_path=$2
+    local iso_path=$3
     if [ "$IRONIC_IPA_RAMDISK_DISTRO" = "coreos" ]; then
-        build_ipa_coreos_ramdisk $kernel_path $ramdisk_path
+        build_ipa_coreos_ramdisk $kernel_path $ramdisk_path $iso_path
     elif [[ "$IRONIC_IPA_RAMDISK_DISTRO" = "fedora" || "$IRONIC_IPA_RAMDISK_DISTRO" = "ubuntu" ]]; then
-        build_ipa_dib_ramdisk $kernel_path $ramdisk_path $IRONIC_IPA_RAMDISK_DISTRO
+        build_ipa_dib_ramdisk $kernel_path $ramdisk_path $iso_path $IRONIC_IPA_RAMDISK_DISTRO
     else
         echo "IRONIC_IPA_RAMDISK_DISTRO=$IRONIC_IPA_RAMDISK_DISTRO is not supported."
     fi
@@ -753,11 +761,15 @@ function build_ipa_coreos_ramdisk {
     echo "Building coreos ironic-python-agent deploy ramdisk"
     local kernel_path=$1
     local ramdisk_path=$2
+    local iso_path=$3
     git_clone $IRONIC_PYTHON_AGENT_REPO $IRONIC_PYTHON_AGENT_DIR $IRONIC_PYTHON_AGENT_BRANCH
     cd $IRONIC_PYTHON_AGENT_DIR
     imagebuild/coreos/build_coreos_image.sh
     cp imagebuild/coreos/UPLOAD/coreos_production_pxe_image-oem.cpio.gz $ramdisk_path
     cp imagebuild/coreos/UPLOAD/coreos_production_pxe.vmlinuz $kernel_path
+    if is_deploy_iso_required; then
+        imagebuild/coreos/iso-image-create -k $kernel_path -i $ramdisk_path -o $iso_path
+    fi
     sudo rm -rf UPLOAD
     cd -
 }
@@ -765,14 +777,21 @@ function build_ipa_coreos_ramdisk {
 function build_ipa_dib_ramdisk {
     local kernel_path=$1
     local ramdisk_path=$2
-    local distro=$3
+    local iso_path=$3
+    local distro=$4
     local tempfile=$(mktemp)
     echo "Building $distro ironic-python-agent deploy ramdisk"
+
+    local image_create_args="$distro ironic-agent"
+    if is_deploy_iso_required; then
+        image_create_args+=" iso"
+    fi
     disk-image-create -a amd64 \
                     -o "$tempfile" \
-                    "$distro" ironic-agent
+                    $image_create_args
     mv "${tempfile}.kernel" "$kernel_path"
     mv "${tempfile}.initramfs" "$ramdisk_path"
+    mv "${tempfile}.iso" "$iso_path"
     rm -f "$tempfile"
 }
 
@@ -791,18 +810,31 @@ function upload_baremetal_ironic_deploy {
     if [ -z "$IRONIC_DEPLOY_KERNEL" -o -z "$IRONIC_DEPLOY_RAMDISK" ]; then
         local IRONIC_DEPLOY_KERNEL_PATH=$TOP_DIR/files/ir-deploy-$IRONIC_DEPLOY_DRIVER.kernel
         local IRONIC_DEPLOY_RAMDISK_PATH=$TOP_DIR/files/ir-deploy-$IRONIC_DEPLOY_DRIVER.initramfs
+        local IRONIC_DEPLOY_ISO_PATH=$TOP_DIR/files/ir-deploy-$IRONIC_DEPLOY_DRIVER.iso
     else
         local IRONIC_DEPLOY_KERNEL_PATH=$IRONIC_DEPLOY_KERNEL
         local IRONIC_DEPLOY_RAMDISK_PATH=$IRONIC_DEPLOY_RAMDISK
+        local IRONIC_DEPLOY_ISO_PATH=$IRONIC_DEPLOY_ISO
     fi
 
-    if [ ! -e "$IRONIC_DEPLOY_RAMDISK_PATH" -o ! -e "$IRONIC_DEPLOY_KERNEL_PATH" ]; then
+    # NOTE: Think of these variables from bash exit code perspective
+    #  iso_required = 0, if iso is required
+    #  iso_required = 1, if iso is not required
+    #  iso_exists = 0, if iso exists
+    #  iso_exists = 1, if iso doesn't exist
+    iso_required=$(is_deploy_iso_required; echo $?)
+    iso_exists=$(test -e $IRONIC_DEPLOY_ISO_PATH; echo $?)
+
+    if [ ! -e "$IRONIC_DEPLOY_RAMDISK_PATH" -o \
+            ! -e "$IRONIC_DEPLOY_KERNEL_PATH" -o \
+            \( "$iso_required" = "0" -a "$iso_exists" = "1" \) ]; then
+
         # files don't exist, need to build them
         if [ "$IRONIC_BUILD_DEPLOY_RAMDISK" = "True" ]; then
             # we can build them only if we're not offline
             if [ "$OFFLINE" != "True" ]; then
                 if is_deployed_with_ipa_ramdisk; then
-                    build_ipa_ramdisk $IRONIC_DEPLOY_KERNEL_PATH $IRONIC_DEPLOY_RAMDISK_PATH
+                    build_ipa_ramdisk $IRONIC_DEPLOY_KERNEL_PATH $IRONIC_DEPLOY_RAMDISK_PATH $IRONIC_DEPLOY_ISO_PATH
                 else
                     ramdisk-image-create $IRONIC_DEPLOY_FLAVOR \
                         -o $TOP_DIR/files/ir-deploy-$IRONIC_DEPLOY_DRIVER
@@ -842,6 +874,16 @@ function upload_baremetal_ironic_deploy {
         --public --disk-format=ari \
         --container-format=ari \
         < $IRONIC_DEPLOY_RAMDISK_PATH  | grep ' id ' | get_field 2)
+
+    if is_deploy_iso_required; then
+        IRONIC_DEPLOY_ISO_ID=$(openstack \
+            --os-token $token \
+            --os-url http://$GLANCE_HOSTPORT \
+            image create \
+            $(basename $IRONIC_DEPLOY_ISO_PATH) \
+            --public --disk-format=iso \
+            --container-format=bare \
+            < $IRONIC_DEPLOY_ISO_PATH  | grep ' id ' | get_field 2)
 }
 
 function prepare_baremetal_basic_ops {
