Functional testing preparation for Ironic
Add ability to create/register qemu vms for Ironic functional testing purposes

https://etherpad.openstack.org/p/IronicDevstackTesting

Change-Id: If452438fcc0ff562531b33a36cd189b235654b48

diff --git a/lib/ironic b/lib/ironic
--- a/lib/ironic
+++ b/lib/ironic
@@ -35,6 +35,26 @@ IRONIC_CONF_FILE=$IRONIC_CONF_DIR/ironic.conf
 IRONIC_ROOTWRAP_CONF=$IRONIC_CONF_DIR/rootwrap.conf
 IRONIC_POLICY_JSON=$IRONIC_CONF_DIR/policy.json
 
+# Set up defaults for functional / integration testing
+TRIPLEO_INCUBATOR_REPO=${TRIPLEO_INCUBATOR_REPO:-https://github.com/openstack/tripleo-incubator}
+TRIPLEO_INCUBATOR_DIR=${TRIPLEO_INCUBATOR_DIR:-$DEST/tripleo-incubator}
+TRIPLEO_INCUBATOR_BRANCH=${TRIPLEO_INCUBATOR_BRANCH:-master}
+IRONIC_BAREMETAL_BASIC_OPS=$(trueorfalse False $IRONIC_BAREMETAL_BASIC_OPS)
+IRONIC_SSH_USERNAME=${IRONIC_SSH_USERNAME:-`whoami`}
+IRONIC_SSH_KEY_DIR=${IRONIC_SSH_KEY_DIR:-$DEST/ssh_keys}
+IRONIC_SSH_KEY_FILENAME=${IRONIC_SSH_KEY_FILENAME:-ironic_key}
+IRONIC_VM_SSH_PORT=${IRONIC_VM_SSH_PORT:-2222}
+IRONIC_VM_SSH_ADDRESS=${IRONIC_VM_SSH_ADDRESS:-127.0.0.1}
+IRONIC_VM_COUNT=${IRONIC_VM_COUNT:-1}
+IRONIC_VM_SPECS_CPU=${IRONIC_VM_SPECS_CPU:-1}
+IRONIC_VM_SPECS_RAM=${IRONIC_VM_SPECS_RAM:-256}
+IRONIC_VM_SPECS_DISK=${IRONIC_VM_SPECS_DISK:-1}
+#use default value for tripleo-incubator create-network script
+IRONIC_VM_NETWORK_BRIDGE=${IRONIC_VM_NETWORK_BRIDGE:-brbm}
+IRONIC_VM_NETWORK_BRIDGE_ADDRESS=${IRONIC_VM_NETWORK_BRIDGE_ADDRESS:-192.0.2.33/24}
+IRONIC_VM_NETWORK_DHCP_RANGE=${IRONIC_VM_NETWORK_DHCP_RANGE:-192.0.2.32,192.0.2.48}
+IRONIC_VM_MACS_CSV_FILE=${IRONIC_VM_MACS_CSV_FILE:-$DEST/ironic_macs.csv}
+
 # Support entry points installation of console scripts
 IRONIC_BIN_DIR=$(get_python_exec_prefix)
 
@@ -96,6 +116,10 @@ function configure_ironic() {
     # Configure Ironic API, if it was enabled.
     if is_service_enabled ir-api; then
         configure_ironic_api
+    fi
+
+    if [[ "$IRONIC_BAREMETAL_BASIC_OPS" == "True" ]]; then
+        configure_ironic_auxiliary
     fi
 }
 
@@ -228,6 +252,141 @@ function stop_ironic() {
     screen -S $SCREEN_NAME -p ir-cond -X kill
 }
 
+function is_ironic() {
+    if ( is_service_enabled ir-cond && is_service_enabled ir-api ); then
+        return 0
+    fi
+    return 1
+}
+
+function configure_ironic_dirs() {
+    # ensure /tftpboot is prepared
+
+    #TODO(agordeev): chown to ironic's user
+    sudo mkdir -p /var/lib/ironic
+    sudo mkdir -p /tftpboot
+    sudo chmod 777 /var/lib/ironic
+    sudo chmod 777 /tftpboot
+    sudo mkdir -p /tftpboot/pxelinux.cfg
+
+    if is_ubuntu; then
+        PXEBIN=/usr/lib/syslinux/pxelinux.0
+    elif is_fedora; then
+        PXEBIN=/usr/share/syslinux/pxelinux.0
+    fi
+    if [ ! -f $PXEBIN ]; then
+        die $LINENO "pxelinux.0 (from SYSLINUX) not found."
+    fi
+
+    sudo cp_it $PXEBIN /tftpboot/
+    sudo chown -R $STACK_USER:$LIBVIRT_GROUP /tftpboot
+}
+
+function start_dnsmasq_for_vms() {
+    #TODO(agordeev): remove this once neutron integration becomes ready
+
+    if ! ps -e | grep dnsmasq | grep /tftpboot; then
+        sudo dnsmasq --conf-file= --port=69 --enable-tftp --tftp-root=/tftpboot --dhcp-boot=pxelinux.0 --pid-file=/var/run/dnsmasq.pid --interface=$IRONIC_VM_NETWORK_BRIDGE --dhcp-range=$IRONIC_VM_NETWORK_DHCP_RANGE
+    fi
+
+}
+
+function create_brigde_and_vms() {
+
+    #TODO(agordeev): remove this once neutron integration becomes ready
+    git_clone $TRIPLEO_INCUBATOR_REPO $TRIPLEO_INCUBATOR_DIR $TRIPLEO_INCUBATOR_BRANCH
+
+    sudo PATH=$PATH:$TRIPLEO_INCUBATOR_DIR/scripts/ $TRIPLEO_INCUBATOR_DIR/scripts/setup-network
+
+    touch $IRONIC_VM_MACS_CSV_FILE
+
+    # create-nodes creates one NIC per VM
+
+    sudo PATH=$PATH:$TRIPLEO_INCUBATOR_DIR/scripts/ $TRIPLEO_INCUBATOR_DIR/scripts/create-nodes $IRONIC_VM_SPECS_CPU $IRONIC_VM_SPECS_RAM $IRONIC_VM_SPECS_DISK amd64 $IRONIC_VM_COUNT | tee -a $IRONIC_VM_MACS_CSV_FILE
+}
+
+function enroll_vms() {
+
+    SOURCE_IMAGE_ID=$(glance image-list | grep $DEFAULT_IMAGE_NAME -m1 | get_field 1)
+
+    CHASSIS_ID=$(ironic chassis-create -d "ironic test chassis" | grep " uuid " | get_field 2)
+    local i=0
+    while read MAC; do
+        NODE_ID=$(ironic node-create --chassis_uuid $CHASSIS_ID --driver pxe_ssh \
+            -i ssh_virt_type=virsh \
+            -i ssh_address=$IRONIC_VM_SSH_ADDRESS \
+            -i ssh_port=$IRONIC_VM_SSH_PORT \
+            -i ssh_username=$IRONIC_SSH_USERNAME \
+            -i ssh_key_filename=$IRONIC_SSH_KEY_DIR/$IRONIC_SSH_KEY_FILENAME \
+            -i pxe_deploy_ramdisk=$BM_DEPLOY_RAMDISK_ID \
+            -i pxe_deploy_kernel=$BM_DEPLOY_KERNEL_ID \
+            -i pxe_instance_name="test-$i" \
+            -i pxe_image_source=$SOURCE_IMAGE_ID \
+            -i pxe_root_gb=$IRONIC_VM_SPECS_DISK \
+            | grep " uuid " | get_field 2)
+
+        ironic port-create --address $MAC --node_uuid $NODE_ID
+
+        ironic node-validate $NODE_ID | grep " power " | get_field 2 | grep result | grep True || die $LINENO "Wrong driver power result"
+        ironic node-validate $NODE_ID | grep " deploy " | get_field 2 | grep result | grep True || die $LINENO "Wrong driver deploy result"
+
+        ironic node-update $NODE_ID replace instance_uuid=`uuidgen`
+        i=$((i+1))
+
+    done < $IRONIC_VM_MACS_CSV_FILE
+}
+
+
+function configure_ironic_ssh_keypair() {
+    # Generating ssh key pair for stack user
+    if [[ ! -d $IRONIC_SSH_KEY_DIR ]]; then
+        mkdir -p $IRONIC_SSH_KEY_DIR
+    fi
+    # avoid overwriting already existent keypair
+    echo -e 'n\n' | ssh-keygen -q -t rsa -P '' -f $IRONIC_SSH_KEY_DIR/$IRONIC_SSH_KEY_FILENAME
+    if [[ ! -d $HOME/.ssh ]]; then
+        mkdir -p $HOME/.ssh
+        chmod 700 $HOME/.ssh
+    fi
+
+    KEY=`cat $IRONIC_SSH_KEY_DIR/$IRONIC_SSH_KEY_FILENAME.pub`
+    if ! grep "$KEY" $HOME/.ssh/authorized_keys; then
+        echo $KEY | tee -a $HOME/.ssh/authorized_keys
+    fi
+
+}
+
+function _ssh_check() {
+    local KEY_FILE=$1
+    local FLOATING_IP=$2
+    local PORT=$3
+    local DEFAULT_INSTANCE_USER=$4
+    local ACTIVE_TIMEOUT=$5
+    if ! timeout $ACTIVE_TIMEOUT sh -c "while ! ssh -p $PORT -o StrictHostKeyChecking=no -i $KEY_FILE ${DEFAULT_INSTANCE_USER}@$FLOATING_IP echo success; do sleep 1; done"; then
+        die $LINENO "server didn't become ssh-able!"
+    fi
+}
+
+function configure_ironic_sshd() {
+    # Ensure sshd server accepts connections from localhost only
+
+    SSH_CONFIG=/etc/ssh/sshd_config
+    HOST_PORT=$IRONIC_VM_SSH_ADDRESS:$IRONIC_VM_SSH_PORT
+    if ! sudo grep ListenAddress $SSH_CONFIG | grep $HOST_PORT; then
+        echo "ListenAddress $HOST_PORT" | sudo tee -a $SSH_CONFIG
+    fi
+
+    restart_service ssh
+
+    _ssh_check $IRONIC_SSH_KEY_DIR/$IRONIC_SSH_KEY_FILENAME $IRONIC_VM_SSH_ADDRESS $IRONIC_VM_SSH_PORT $IRONIC_SSH_USERNAME 10
+
+}
+
+function configure_ironic_auxiliary() {
+    configure_ironic_dirs
+    configure_ironic_ssh_keypair
+    configure_ironic_sshd
+}
 
 # Restore xtrace
 $XTRACE
