Add MONGO_DEB variable to config Mongo version
Now all gating machines are installed with very old Mongo. We need to configure this
for creating gating jobs on new MongoDB for Ceilometer.

Change-Id: I048bbc5ea69a2ebfa4b717f70605147e51b84733

diff --git a/lib/marconi b/lib/marconi
--- a/lib/marconi
+++ b/lib/marconi
@@ -120,6 +120,20 @@ function configure_marconi {
 function configure_mongodb {
     # Set nssize to 2GB. This increases the number of namespaces supported
     # # per database.
+    if [ -n "$MONGO_DEB" ]; then
+        if !is_ubuntu; then
+            echo "Cannot apply MONGO_DEB on non-ubuntu system"
+            exit 1
+        fi
+        wget "$MONGO_DEB" -O "/tmp/mongo.deb"
+        dpkg -i "/tmp/mongo.deb"
+    else
+        install_package mongodb-server
+        if !is_ubuntu; then
+            install_package mongodb
+        fi
+    fi
+
     if is_ubuntu; then
         sudo sed -i -e "
             s|[^ \t]*#[ \t]*\(nssize[ \t]*=.*\$\)|\1|
