Make exercise.sh with devstack work
- added support for quantum-debug command
- added ping and ssh method for quantum

Change-Id: Iebf8a0e9e2ed2bb56bee6533e69827e6caa2bc82

diff --git a/lib/quantum b/lib/quantum
--- a/lib/quantum
+++ b/lib/quantum
@@ -57,5 +57,55 @@ function is_quantum_ovs_base_plugin() {
     return 1
 }
 
+function _get_net_id() {
+    quantum net-list | grep $1 | awk '{print $2}'
+}
+
+function _get_probe_cmd() {
+    local from_net="$1"
+    net_id=`_get_net_id $from_net`
+    probe_id=`quantum-debug --os-tenant-name admin --os-username admin probe-list -c id -c network_id | grep $net_id | awk '{print $2}'`
+    echo "sudo ip netns exec qprobe-$probe_id"
+}
+
+function delete_probe() {
+    local from_net="$1"
+    net_id=`_get_net_id $from_net`
+    probe_id=`quantum-debug --os-tenant-name admin --os-username admin probe-list -c id -c network_id | grep $net_id | awk '{print $2}'`
+    quantum-debug --os-tenant-name admin --os-username admin probe-delete $probe_id
+}
+
+function _ping_check_quantum() {
+    local from_net=$1
+    local ip=$2
+    local boot_timeout=$3
+    local expected=$4
+    probe_cmd=`_get_probe_cmd $from_net`
+    if ! timeout $boot_timeout sh -c "while ! $probe_cmd ping -c1 -w1 $ip; do sleep 1; done"; then
+        echo "Couldn't ping server"
+        if [[ "$expected" = "Fail" ]]; then
+            return
+        else
+            exit 1
+        fi
+    fi
+}
+
+# ssh check
+function _ssh_check_quantum() {
+    local from_net=$1
+    local KEY_FILE=$2
+    local FLOATING_IP=$3
+    local DEFAULT_INSTANCE_USER=$4
+    local ACTIVE_TIMEOUT=$5
+    local probe_cmd = ""
+    probe_cmd=`_get_probe_cmd $from_net`
+    if ! timeout $ACTIVE_TIMEOUT sh -c "while ! $probe_cmd ssh -o StrictHostKeyChecking=no -i $KEY_FILE ${DEFAULT_INSTANCE_USER}@$FLOATING_IP echo success ; do sleep 1; done"; then
+        echo "server didn't become ssh-able!"
+        exit 1
+    fi
+}
+
+
 # Restore xtrace
 $XTRACE
