Fix benign epmd@0.0.0.0.socket failure
* The restart loop for rabbitmq-server can trigger socket activation
  of epmd without rabbitmq-server running. This can lead to 'systemctl
  status' reporting 'State: degraded' with no simple way to reset to
  'State: running'.
* It's important to note that this socket activation failure is benign
  and is not an indicator of system failure.

Change-Id: Iede4f5ebeffb59644dee4a17b6331b3cdd04d146
Signed-off-by: Jan Gutter <jan.gutter@netronome.com>

diff --git a/lib/rpc_backend b/lib/rpc_backend
--- a/lib/rpc_backend
+++ b/lib/rpc_backend
@@ -76,6 +76,17 @@ function restart_rpc_backend {
     if is_service_enabled rabbit; then
         # Start rabbitmq-server
         echo_summary "Starting RabbitMQ"
+        local rc=0
+
+        # NOTE(jangutter): If rabbitmq is not running (as in a fresh install)
+        # then rabbit_setuser triggers epmd@0.0.0.0.socket with socket
+        # activation. This fails the first time and does not get cleared.
+        # It is benign, but the workaround is to start rabbitmq a bit earlier.
+        systemctl --quiet is-running rabbitmq-server.service || rc=$?
+        if [ $rc -ne 0 ]; then
+            restart_service rabbitmq-server
+        fi
+
         # NOTE(bnemec): Retry initial rabbitmq configuration to deal with
         # the fact that sometimes it fails to start properly.
         # Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1144100
@@ -88,7 +99,7 @@ function restart_rpc_backend {
         # service file.
         local i
         for i in `seq 20`; do
-            local rc=0
+            rc=0
 
             [[ $i -eq "20" ]] && die $LINENO "Failed to set rabbitmq password"
 
