create and use RABBIT_USERID instead of 'guest'.
Newer versions of rabbitmq (3.3 and later) do not allow the 'guest'
user to access on non-local interfaces.

Add the RABBIT_USERID configuration variable, which defaults to 'stackrabbit'.
Create and use that user instead of using the default 'guest'.

Closes-Bug: #1343354
Change-Id: I7f4e5aedc41f21d06b783a1faeb3e2552051032f

diff --git a/lib/rpc_backend b/lib/rpc_backend
--- a/lib/rpc_backend
+++ b/lib/rpc_backend
@@ -5,7 +5,7 @@
 # Dependencies:
 #
 # - ``functions`` file
-# - ``RABBIT_{HOST|PASSWORD}`` must be defined when RabbitMQ is used
+# - ``RABBIT_{HOST|PASSWORD|USERID}`` must be defined when RabbitMQ is used
 
 # ``stack.sh`` calls the entry points in this order:
 #
@@ -63,6 +63,9 @@ function check_rpc_backend {
 function cleanup_rpc_backend {
     if is_service_enabled rabbit; then
         # Obliterate rabbitmq-server
+        if [ -n "$RABBIT_USERID" ]; then
+            sudo rabbitmqctl delete_user "$RABBIT_USERID"
+        fi
         uninstall_package rabbitmq-server
         sudo killall epmd || sudo killall -9 epmd
         if is_ubuntu; then
@@ -147,10 +150,13 @@ function restart_rpc_backend {
                 # service is not started by default
                 restart_service rabbitmq-server
             fi
-            # change the rabbit password since the default is "guest"
-            sudo rabbitmqctl change_password guest $RABBIT_PASSWORD && break
+            # verify we can communicate before going on
+            sudo rabbitmqctl list_users 2>/dev/null && break
             [[ $i -eq "10" ]] && die $LINENO "Failed to set rabbitmq password"
         done
+        # set the rabbit user/password
+        rabbit_setuser "$RABBIT_USERID" "$RABBIT_PASSWORD" ||
+            die $LINENO "Failed to create/set user '$RABIIT_USERID'"
         if is_service_enabled n-cell; then
             # Add partitioned access for the child cell
             if [ -z `sudo rabbitmqctl list_vhosts | grep child_cell` ]; then
@@ -188,6 +194,7 @@ function iniset_rpc_backend {
         iniset $file $section rpc_backend ${package}.openstack.common.rpc.impl_kombu
         iniset $file $section rabbit_hosts $RABBIT_HOST
         iniset $file $section rabbit_password $RABBIT_PASSWORD
+        iniset $file $section rabbit_userid $RABBIT_USERID
     fi
 }
 
@@ -202,6 +209,20 @@ function qpid_is_supported {
     ( ! is_suse )
 }
 
+function rabbit_setuser {
+   local user="$1" pass="$2" found="" out=""
+   out=$(sudo rabbitmqctl list_users) ||
+      { echo "failed to list users" 1>&2; return 1; }
+   found=$(echo "$out" | awk '$1 == user { print $1 }' "user=$user")
+   if [ "$found" = "$user" ]; then
+       sudo rabbitmqctl change_password "$user" "$pass" ||
+          { echo "failed changing pass for '$user'" 1>&2; return 1; }
+   else
+       sudo rabbitmqctl add_user "$user" "$pass" ||
+          { echo "failed changing pass for $user"; return 1; }
+   fi
+   sudo rabbitmqctl set_permissions "$user" ".*" ".*" ".*"
+}
 
 # Restore xtrace
 $XTRACE
