Fixes rabbitmq restart bug in Vivid
This change validates that rabbitmq-server isn't running or if it fails
to report a properly running service before trying to restart it

Change-Id: I7ef7e3366aa3ea91bcddfcf0400931635efdb3aa
Closes-Bug: #1460799

diff --git a/lib/rpc_backend b/lib/rpc_backend
--- a/lib/rpc_backend
+++ b/lib/rpc_backend
@@ -50,6 +50,20 @@ function install_rpc_backend {
     fi
 }
 
+# verify rpc backend
+# rabbitmqctl wrapper to verify status services
+function verify_rpc_backend_status {
+    local rc=1
+    if is_ubuntu; then
+        sudo /usr/sbin/rabbitmqctl status > /dev/null 2>&1
+        rc=$?
+    else
+        sudo /sbin/rabbitmqctl status > /dev/null 2>&1
+        rc=$?
+    fi
+    return $rc
+}
+
 # restart the rpc backend
 function restart_rpc_backend {
     if is_service_enabled rabbit; then
@@ -66,14 +80,15 @@ function restart_rpc_backend {
         # TODO(tonyb): Remove this when Debian and Ubuntu have a fixed systemd
         # service file.
         local i
+
         for i in `seq 20`; do
             local rc=0
 
-            [[ $i -eq "20" ]] && die $LINENO "Failed to set rabbitmq password"
+  	    if ! service_status rabbitmq-server || ! verify_rpc_backend_status; then
+		restart_service rabbitmq-server
+	    fi
 
-            if [[ $(( i % 2 )) == "0" ]] ; then
-                restart_service rabbitmq-server
-            fi
+            [[ $i -eq "20" ]] && die $LINENO "Failed to set rabbitmq password"
 
             rabbit_setuser "$RABBIT_USERID" "$RABBIT_PASSWORD" || rc=$?
             if [ $rc -ne 0 ]; then
